import { describe, expect, it } from "vitest";
import { runsOf } from "./clues";
import { solveLine } from "./line";
import { BLANK, FILLED, UNKNOWN, type Clue } from "./types";

const line = (...v: number[]) => Uint8Array.from(v);
const U = UNKNOWN, F = FILLED, B = BLANK;

/** Every line of length n matching `clue`, generated by exhaustive search. */
function allMatching(clue: Clue, n: number): Uint8Array[] {
  const out: Uint8Array[] = [];
  for (let mask = 0; mask < 1 << n; mask++) {
    const candidate = new Uint8Array(n);
    for (let i = 0; i < n; i++) candidate[i] = (mask >> i) & 1 ? FILLED : BLANK;
    if (runsOf(candidate).join(",") === clue.join(",")) out.push(candidate);
  }
  return out;
}

/** What brute force says is forced, given a partially known line. */
function forcedByBruteForce(known: Uint8Array, clue: Clue): Uint8Array | null {
  const viable = allMatching(clue, known.length).filter((cand) =>
    cand.every((v, i) => known[i] === UNKNOWN || known[i] === v),
  );
  if (viable.length === 0) return null;

  const out = new Uint8Array(known.length);
  for (let i = 0; i < known.length; i++) {
    const first = viable[0][i];
    out[i] = viable.every((cand) => cand[i] === first) ? first : UNKNOWN;
  }
  return out;
}

describe("solveLine", () => {
  it("fills a line whose clue exactly spans it", () => {
    const r = solveLine(line(U, U, U), [3]);
    expect(r.status).toBe("ok");
    if (r.status !== "ok") return;
    expect([...r.line]).toEqual([F, F, F]);
    expect(r.changed).toBe(3);
  });

  it("forces the overlap of a run too big to slide freely", () => {
    // A run of 3 in 4 cells must cover the middle two wherever it sits.
    const r = solveLine(line(U, U, U, U), [3]);
    expect(r.status).toBe("ok");
    if (r.status !== "ok") return;
    expect([...r.line]).toEqual([U, F, F, U]);
  });

  it("blanks every cell when the clue is empty", () => {
    const r = solveLine(line(U, U), []);
    expect(r.status).toBe("ok");
    if (r.status !== "ok") return;
    expect([...r.line]).toEqual([B, B]);
  });

  it("reports a contradiction when no placement fits", () => {
    expect(solveLine(line(B, B), [1]).status).toBe("contradiction");
    expect(solveLine(line(F, U), []).status).toBe("contradiction");
  });

  it("never contradicts a cell the caller already knew", () => {
    const r = solveLine(line(F, U, U, U), [1, 1]);
    expect(r.status).toBe("ok");
    if (r.status !== "ok") return;
    expect(r.line[0]).toBe(F);
    expect(r.line[1]).toBe(B);
  });

  it("agrees with brute force on every clue and every partial line", () => {
    const N = 8;
    const clues: Clue[] = [[], [1], [3], [8], [1, 1], [2, 3], [1, 1, 1], [2, 1, 2]];

    for (const clue of clues) {
      // 3^N partial lines is too many; sample deterministically instead.
      for (let seed = 0; seed < 400; seed++) {
        const known = new Uint8Array(N);
        let s = seed * 2654435761;
        for (let i = 0; i < N; i++) {
          s = (s ^ (s >>> 13)) * 1274126177;
          known[i] = [UNKNOWN, UNKNOWN, FILLED, BLANK][(s >>> 3) & 3];
        }

        const expected = forcedByBruteForce(known, clue);
        const actual = solveLine(known, clue);

        if (expected === null) {
          expect(actual.status).toBe("contradiction");
        } else {
          expect(actual.status).toBe("ok");
          if (actual.status !== "ok") continue;
          expect([...actual.line]).toEqual([...expected]);
        }
      }
    }
  });
});
